### ISSUE TITLE
Can't seem to use media queries with electron

### ISSUE THREAD

**Issue by LCordial** [Ambience-Studios/ambience.mbm#4]
**Describe the bug**
Text does not resize with the electron app. I tried to use media queries, these do not work. I can't seem to find documentation on this.

**To Reproduce**
1. Go to 'main.css'
2. Write: 
```css
@media only screen and (max-width: 600px){
     .title{
           color: red;
     }
```
**You'll need to create a text element in HTML and add CSS to the text element**
3. Run `npm run start`, change window size and the text does not change colour.

**Expected behavior**
The text would change colour when the window is resized.

**Comment by LCordial** [comment]
I don't know if it is relevant to the project.

**Comment by RepeatedRoot** [comment]
Text will in fact change colour when resizing the app, but you have to also provide a default value to fall back on when the media query event is not fulfilled.

``` css
/* The default colour */
h1 {
    color: #ddd;
}

/* Change the colour to red when the window is less than 600px wide */
@media only screen and (max-width: 600px){
    h1 {
        color: #f00;
    }
}
```
Because with the method shown before there is no 'fall back' colour in the event the media event does not trigger
